// Generated by CIRCT unknown git version
module NOI(	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:2:3
  input clock,	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:2:21
        reset,	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:2:45
        a,	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:2:61
        b	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:2:73
);

  reg hbr = 1'h0;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:8:12
  always_ff @(posedge clock)	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:8:12
    hbr <= reset | hbr;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:7:10, :8:12
  reg delay_ = 1'h0;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:18:15
  reg antecedent_0 = 1'h0;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:20:21
  always_ff @(posedge clock) begin	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:20:21
    if (reset) begin	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:20:21
      delay_ <= 1'h0;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:18:15
      antecedent_0 <= 1'h0;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:20:21
    end
    else begin	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:20:21
      delay_ <= delay_ | delay_ - 1'h1;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:14:10, :17:10, :18:15
      antecedent_0 <= a;	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:20:21
    end
  end // always_ff @(posedge)
  always @(posedge clock)	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:28:5
    assert(~(hbr & ~reset) | ~delay_ | ~antecedent_0 | b | reset);	// ../firrtl-examples/mlir/loweredbasicnoi.mlir:8:12, :9:10, :10:10, :11:10, :18:15, :20:21, :21:10, :23:10, :24:11, :25:11, :26:11, :27:11, :29:7
endmodule
